### ISSUE TITLE
Feature request: Load default file settings if exist

### ISSUE THREAD

**Issue by duhow** [docker/setup-buildx-action#127]
**Context**

I am using self-hosted runners with [actions-runner-controller](https://github.com/actions-runner-controller/actions-runner-controller), and setup a [local registry mirror](https://docs.docker.com/registry/recipes/mirror/).
All runners have this file mounted in `/etc/buildkit/buildkitd.toml`:

```
[registry."docker.io"]
  mirrors = ["docker-registry:5000"]

[registry."docker-registry:5000"]
  http = true
```

**Request**

If file `/etc/buildkit/buildkitd.toml` exists and no other `config` or `config-inline` was specified at step, use the file with `--config`, so there's no need to specify this value in the workflows.

**Comment by tonistiigi** [comment]
Something like this has been asked in buildx repository as well. I think we shouldn't use `/etc/buildkit/buildkitd.toml` because that is reserved to `buildkitd` running on the host but we could potentially load something like `~/.docker/buildx/buildkitd.default.toml`.

**Comment by crazy-max** [comment]
> but we could potentially load something like `~/.docker/buildx/buildkitd.default.toml`.

Yes sgtm too.
