### ISSUE TITLE
daemon side entitlements could be allowed by default

### ISSUE THREAD

**Issue by tonistiigi** [docker/setup-buildx-action#13]
As discussed in one of the early PRs because actions run in a VM it should be fine to set the daemon entitlements with `--buildkitd-flags` by default so build action could use `allow` without special configuration. I think it could just be a default value for `buildkitd-flags`. If user wants to provide own flags they could also set new entitlements list.

**Comment by crazy-max** [comment]
@tonistiigi Ok so `--allow-insecure-entitlement security.insecure` by default?

**Comment by tonistiigi** [comment]
@crazy-max Yes, `--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host`
