### ISSUE TITLE
step is stuck in download

### ISSUE THREAD

**Issue by thehungrycoder** [docker/setup-buildx-action#137]
,,ki've self-hosted runners in DigitalOcean kubernetes. It was working fine until recently. Now, it is stuck in setup-buildx-action step while downloading the runner. 

![Screen Shot 2022-04-14 at 1 25 32 PM](https://user-images.githubusercontent.com/79018/163441621-ac10c0c3-6ee7-41ea-ab47-ea57e04fff02.png)
(i manually canceled after long time)

I've same action that is running in github provided workers (ubuntu-latest) and they're working fine. 

Is it networking problem? If I get into any container and try to download the file it works!

Any idea what could be wrong and what I can try? Thanks in advance

**Comment by crazy-max** [comment]
This is a kernel issue, see https://github.com/docker/setup-buildx-action/issues/117 for more details.

**Comment by thehungrycoder** [comment]
Thanks for the info. I tried to follow as much as I understood but couldn't find it in working state. I'll keep researching.
