### ISSUE TITLE
Github Action Failing:   Error: The process '/usr/bin/docker' failed with exit code 1

### ISSUE THREAD

**Issue by EvoChristopherShaw** [docker/setup-buildx-action#166]
### Behaviour

Github Actions Failing

#### Steps to reproduce this issue

1. Call The Action During Workflow

#### Expected behaviour

To complete sucessfully

#### Actual behaviour

Run docker/setup-buildx-action@v1
  with:
    driver: docker-container
    buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    install: false
    use: true
  env:
    TARGET_BRANCH_NAME: merge
    IMAGE_TAG: evo-7957
    GENERATED_HASH: 4[2](https://github.com/EvolutionFunding/main/actions/runs/3088622826/jobs/4995881633#step:7:2)a99[4](https://github.com/EvolutionFunding/main/actions/runs/3088622826/jobs/4995881633#step:7:4)f0eb427022
    JIRA_EVO_NUMBER: EVO-79[5](https://github.com/EvolutionFunding/main/actions/runs/3088622826/jobs/4995881633#step:7:5)7
Docker info
  /usr/bin/docker version
  Client: Docker Engine - Community
   Version:           20.10.14
   API version:       1.41
   Go version:        go1.1[6](https://github.com/EvolutionFunding/main/actions/runs/3088622826/jobs/4995881633#step:7:6).15
   Git commit:        a2240[8](https://github.com/EvolutionFunding/main/actions/runs/3088622826/jobs/4995881633#step:7:8)6
   Built:             Thu Mar 24 01:48:21 [20](https://github.com/EvolutionFunding/main/actions/runs/3088622826/jobs/4995881633#step:7:21)[22](https://github.com/EvolutionFunding/main/actions/runs/3088622826/jobs/4995881633#step:7:23)
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Error: The process '/usr/bin/docker' failed with exit code 1

**Comment by crazy-max** [comment]
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Looks like daemon is not running on your runner. Can you post your workflow or a link to your repo to have a look?

**Comment by EvoChristopherShaw** [comment]
Its a private company repo so cannot share. The workflow was working fine until this morning.

**Comment by EvoChristopherShaw** [comment]
We have tried both v1 and v2

![image](https://user-images.githubusercontent.com/105783738/191222723-b79bfc6b-ba66-4a4d-8c67-ff81e95725a7.png)

and for how we are invoking the action,


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

**Comment by crazy-max** [comment]
Can you post the complete workflow? Would like to know if you're using a self-hosted (`run-on` field) but looking at the screenshot you're not using a public GitHub runner. Public runners have Docker 20.10.17 installed atm and no issue using them on our side: https://github.com/docker/setup-buildx-action/actions/runs/3081535752/jobs/4980192528#step:3:134

Looks like your runner environment is faulty and not an issue with the action. Closing this issue since that should answer your question. Let us know if you have any other information. Thanks.

**Comment by EvoChristopherShaw** [comment]
Thanks for the support, it did turn out to be an environment issue.
