### ISSUE TITLE
ecr scan fail after build on buildx

### ISSUE THREAD

**Issue by kimsw61** [docker/setup-buildx-action#186]
#### Steps to reproduce this issue

1. ecr scan fail after arm64 build from buildx

#### Expected behaviour

> I builded through github action with buildx using 2.2.1

   but next step (ecr scan) is failed.

  error message is on the below.

  "An artifact with media type 'application/vnd.oci.image.index.v1+json' cannot be scanned. For more information, see the Amazon ECR documentation."

#### Actual behaviour

> actually, i used on v2 before, after issue, I was changed v2 to v2.2.1

#### Command

> docker buildx build . -f infra/Dockerfile --platform=linux/arm64 -t $ECR_REGISTRY/stg-$ECR_REPOSITORY:$IMAGE_TAG --push

**Comment by tonistiigi** [comment]
https://github.com/moby/buildkit/issues/3499

**Comment by kimsw61** [comment]
i got answer from aws global communication center under below.

what should i do for fix this error?
-----------------------------------------------------------
In the error information, we have confirmed that there is an artifact of 'Application/vND.OCI.IMAGE.INDEX.V1+JSON' IMAGE Manifest. You can see that ECR does not support multiple architecture image scanes [1].
 
The first Amazon ECR Scan Repositories deals with the following supported media types: See [2].
 
* "Application/vND.DOCKER.DISTRIBUTION.MANIFEST.V1+JSON"
 
* "Application/vND.DOCKER.DISTRIBUTION.MANIFEST.V1+Prettyjws"
 
* "Application/vN.oci.image.Manifest.v1+json"
 
* "Application/vND.DOCKER.DISTRIBUTION.MANIFEST.V2+JSON"
 
Scratch images and DockERV2LISTMEDYATYPE images are not supported.
 
The problem [3] was released on a public container roadmap and found that the same function was required. At this time, the ECR team cannot see the roadmap for this feature. This feature is a feature inside the ECR service team, so you can't provide ETA to use it.

**Comment by jedevc** [comment]
Closing in preference of https://github.com/moby/buildkit/issues/3499.
