### ISSUE TITLE
Context builder cannot be removed - cleanup warning

### ISSUE THREAD

**Issue by ravwojdyla** [docker/setup-buildx-action#188]
### Behaviour

Warning from `Removing builder` stage:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/1419010/213879200-0d7f3677-bbdc-42be-8bd4-0b8d4e11c3b6.png">

#### Steps to reproduce this issue

Usage:

```yaml
- uses: docker/setup-buildx-action@v2
  id: buildx
  with:
    driver: docker
    install: true
```

### Logs

```
Post job cleanup.
Removing builder
  /usr/bin/docker buildx rm default
  ERROR: context builder cannot be removed, run `docker context rm default` to remove this context
  Warning: ERROR: context builder cannot be removed, run `docker context rm default` to remove this context
Cleaning up credentials
```

**Comment by jedevc** [comment]
We've merged a fix for this upstream in buildx - https://github.com/docker/buildx/pull/1547.

This fix will be added into buildx v0.10.1 when it is released (hopefully soon :tada:)
