### ISSUE TITLE
Adding driver-opts to append breaks

### ISSUE THREAD

**Issue by DavidS-om** [docker/setup-buildx-action#214]
#### Steps to reproduce this issue

```yaml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
  with:
    driver: kubernetes
    platforms: linux/amd64
    driver-opts: |
      "namespace=buildkit"
      "nodeselector=""kubernetes.io/arch=arm64"""
    append: |
      - platforms: linux/arm64
        driver-opts: |
          "namespace=buildkit"
          "nodeselector=""kubernetes.io/arch=arm64"""
```

#### Expected behaviour

create a builder with one amd64 and one arm64 node using the same syntax

#### Actual behaviour

Appending the node fails with 
```
   /usr/bin/docker buildx create --name builder-6f13477c-e275-4577-9162-3dd2922f93d1 --append --driver-opt n --driver-opt a --driver-opt m --driver-opt e --driver-opt s --driver-opt p --driver-opt a --driver-opt c --driver-opt e --driver-opt = --driver-opt b --driver-opt u --driver-opt i --driver-opt l --driver-opt d --driver-opt k --driver-opt i --driver-opt t --driver-opt 
   --driver-opt n --driver-opt o --driver-opt d --driver-opt e --driver-opt s --driver-opt e --driver-opt l --driver-opt e --driver-opt c --driver-opt t --driver-opt o --driver-opt r --driver-opt = --driver-opt " --driver-opt k --driver-opt u --driver-opt b --driver-opt e --driver-opt r --driver-opt n --driver-opt e --driver-opt t --driver-opt e --driver-opt s --driver-opt . --driver-opt i --driver-opt o --driver-opt / --driver-opt a --driver-opt r --driver-opt c --driver-opt h --driver-opt = --driver-opt a --driver-opt r --driver-opt m --driver-opt 6 --driver-opt 4 --driver-opt " --driver-opt 
   --platform linux/arm64
  ERROR: invalid value "n", expecting k=v
```

![2023-03-07_11MS+0100_885x865](https://user-images.githubusercontent.com/118179693/223396044-91f127ee-8abc-429d-bd63-78daa2d67fb2.png)

**Comment by DavidS-om** [comment]
I was able to get this to work using
```yaml
          append: |
            - platforms: linux/arm64
              driver-opts:
                - '"namespace=buildkit"'
                - '"nodeselector=""kubernetes.io/arch=arm64"""'
```

(note the multiple levels of quotes)

but then ran straight into #215

**Comment by crazy-max** [comment]
@DavidS-om 

```
        driver-opts: |
          "namespace=buildkit"
          "nodeselector=""kubernetes.io/arch=arm64"""
```

`driver-opts` is an array, not a string as shown in https://docs.docker.com/build/ci/github-actions/configure-builder/#append-additional-nodes-to-the-builder.

See also https://github.com/docker/setup-buildx-action/blob/4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c/.github/workflows/ci.yml#L435-L448

**Comment by DavidS-om** [comment]
> `driver-opts` for the `append` input is an array, not a string

oh yeah, I know. Now. After hours of painful struggles.

That's why I wrote "create a builder with one amd64 and one arm64 node **using the same syntax**" under expected behavior.

**Comment by crazy-max** [comment]
> That's why I wrote "create a builder with one amd64 and one arm64 node **using the same syntax**" under expected behavior.

Ah sorry I overlooked this in your issue. I would also prefer to use the same syntax but we are currently limited by the GitHub toolkit as inputs can only be a string type. We could also have used  a string for `driver-opts` to avoid confusion though.

**Comment by DavidS-om** [comment]
It's my own fault for writing a confusing issue while I was still figuring this out.

Yes, using (allowing) the same syntax as the top-level opts would be a great thing. Everyone already has to figure that out (thanks, microsoft!) and then being able to copy/paste/modify instead of having to learn/lookup a new syntax would have helped me a lot.
