### ISSUE TITLE
buildx failed with: ERROR: Error response from daemon: Windows does not support privileged mode

### ISSUE THREAD

**Issue by major0** [docker/setup-buildx-action#228]
### Behaviour

The docker/build-push action fails with setup-buildx-action on Windows and I can find no docs for how to configure buildx to get the build to work on windows.

I assume that ever since this change <https://github.com/testcontainers/moby-ryuk/pull/40> that building on Windows should available.

#### Steps to reproduce this issue

1. Run a docker build with `runs-on: windows-latest`

#### Expected behaviour

Build completes

#### Actual behaviour

Build fails

### Configuration

```
runs-on: windows-latest
```

### Logs

```
ERROR: Error response from daemon: Windows does not support privileged mode
Error: buildx failed with: ERROR: Error response from daemon: Windows does not support privileged mode
```

**Comment by crazy-max** [comment]
Looking at https://github.com/testcontainers/moby-ryuk/pull/40, you want to build a Windows image. BuildKit does not support Windows containers yet (currently tracked in https://github.com/moby/buildkit/issues/616).

Also I'm able to repro:

```yaml
jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
```

![image](https://user-images.githubusercontent.com/1951866/232381946-5e48f851-dcc5-447e-83ff-fda8e35bff4e.png)

But the action does not seem to fail:

![image](https://user-images.githubusercontent.com/1951866/232382985-1ac92471-4bb7-4a83-ae4e-e8d38d032644.png)

This might be something we need to fix upstream.
