### ISSUE TITLE
Node16 Deprecation

### ISSUE THREAD

**Issue by kinano** [docker/setup-buildx-action#263]
Node16 will be deprecated on 09/11/2023 ([link](https://nodejs.org/en/blog/announcements/nodejs16-eol)). 

Node 16 is used by the action at the moment according to the source code: https://github.com/docker/setup-buildx-action/blob/a52126db3ddbe9872eba76f28f014a43d05b19aa/action.yml#L68-L69

Is there a plan to release a node version update soon?

**Comment by crazy-max** [comment]
Same as https://github.com/docker/setup-qemu-action/issues/100#issuecomment-1708361205. Please avoid posting the same issue on each repo.

**Comment by crazy-max** [comment]
https://github.com/docker/setup-buildx-action/releases/tag/v3.0.0
