### ISSUE TITLE
Update to node20 appears to be a breaking change

### ISSUE THREAD

**Issue by wrose504** [docker/setup-buildx-action#276]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

A recent commit (02e93192) switched the runner version for the action to `node20` from `node16`. On our self-hosted Github Enterprise server, this results in actions failing with the error.

### Expected behaviour

Ideally, a change to the runner to a newer version that is possibly unsupported everywhere would be tagged with a new label (e.g. no longer `v3.0.0`) so we could continue to use the supported version.

### Actual behaviour

Our actions are failing with an error:

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load docker/setup-buildx-action/v3/action.yml
```

### YAML workflow

```yaml
name: Test GraphQL
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-app-image:
    name: Build app image
    needs: []
    runs-on: [standard]
    outputs:
      image: app-dev:${{github.sha}}
    env:
      DOCKER_CONTEXT: gha
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Create Docker context
        run: docker context create ${{env.DOCKER_CONTEXT}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{env.DOCKER_CONTEXT}}
          install: true
```

**Comment by wrose504** [comment]
So this may have been filed a little prematurely: we updated our Github actions runner image from `v2.306.0-ubuntu-20.04` to `v2.309.0-ubuntu-20.04` and `node20` is accepted now.

**Comment by crazy-max** [comment]
@wrose504 Yes as said in the release notes it requires a minimal version of the runner: https://github.com/docker/setup-buildx-action/releases/tag/v3.0.0

> ... (requires [Actions Runner v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later) by @crazy-max in https://github.com/docker/setup-buildx-action/pull/264
