### ISSUE TITLE
Error: The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20

### ISSUE THREAD

**Issue by mconigliaro** [docker/setup-buildx-action#278]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Error: The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20

### Expected behaviour

I expected not to get an error message

### Actual behaviour

I get an error message

### YAML workflow

```yaml
name: Docker build and push

on:
  workflow_call

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3
```

### Workflow logs

```
$ act --env-file .env.ephemeral -W .github/workflows/docker-build-push.yml
[Docker build and push/build-push] 🚀  Start image=catthehacker/ubuntu:act-latest
[Docker build and push/build-push]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[Docker build and push/build-push]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Docker build and push/build-push]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Docker build and push/build-push]   ☁  git clone 'https://github.com/docker/setup-buildx-action' # ref=v3
[Docker build and push/build-push] 🏁  Job succeeded
Error: The runs.using key in action.yml must be one of: [composite docker node12 node16], got node20
```

**Comment by crazy-max** [comment]
> `$ act`

Same as https://github.com/docker/setup-buildx-action/issues/53, act is not officially supported and therefore might diverge with public runners. In this case they don't seem support `node20` runtime.
