### ISSUE TITLE
Support Windows Agents

### ISSUE THREAD

**Issue by gburkecw** [docker/setup-buildx-action#292]
### Description

Attempting to use this action on 'windows-latest' agents results in the following error during "Booting builder":

C:\Windows\system32\docker.exe buildx inspect --bootstrap --builder builder-6b9f230d-ee8f-43d3-a89f-71c9c655a311
  #1 [internal] booting buildkit
  #1 pulling image moby/buildkit:buildx-stable-1
  #1 pulling image moby/buildkit:buildx-stable-1 2.4s done
  #1 creating container buildx_buildkit_builder-6b9f230d-ee8f-43d3-a89f-71c9c655a3110 done
  #1 ERROR: Error response from daemon: Windows does not support privileged mode
  ------
   > [internal] booting buildkit:
  ------
  ERROR: Error response from daemon: Windows does not support privileged mode
Error: The process 'C:\Windows\system32\docker.exe' failed with exit code 1

**Comment by crazy-max** [comment]
> ```
> ERROR: Error response from daemon: Windows does not support privileged mode
> ```

Same as https://github.com/docker/setup-buildx-action/issues/228#issuecomment-1510707981

Why are you using Windows runners? Are you building a Windows container image? If that's the case, BuildKit does not support Windows containers yet. This is tracked in https://github.com/moby/buildkit/issues/616

**Comment by Togtja** [comment]
There is now experimental support for Windows, and I was wondering if setup buildx action would attempt to support the windows buildx?

**Comment by cwoodhayes** [comment]
+1

**Comment by crazy-max** [comment]
> There is now experimental support for Windows, and I was wondering if setup buildx action would attempt to support the windows buildx?

cc @colinhemmings

**Comment by ericoporto** [comment]
I really would like this to work
