### ISSUE TITLE
Using buildx latest by default is risky

### ISSUE THREAD

**Issue by neilime** [docker/setup-buildx-action#309]
If the buildx version is not provided in input the used buildx version is `latest`: https://github.com/docker/setup-buildx-action/blob/2b51285047da1547ffb1b2203d8be4c0af6b1f20/src/main.ts#L45

This is a risky pattern, as some unexpected behavior may occurs (if buildx release a new version) without any change from the user of the action.
I suggest to fix the version, to ensure that setup-buildx-action remains stable and idempotent

**Comment by crazy-max** [comment]
It downloads latest buildx version only if not installed on the runner.

**Comment by neilime** [comment]
Yes that's what I'm pointing out

**Comment by crazy-max** [comment]
Buildx is already installed on GitHub Public runners. It could happen on self-hosted runners but that's an edge case. Also Buildx is backward compatible so don't think we should pin in this action. If you encounter backward compat issues, please report them at https://github.com/docker/buildx
