### ISSUE TITLE
How do save the compiled image as a "tar"

### ISSUE THREAD

**Issue by bigbugcc** [docker/setup-buildx-action#325]
### Description

I appreciate that this project builds multi-platform images very quickly, but I would like to export the compiled image as a tarball to make it easier for me to download it and use it on my LAN; something like `docker save` in docker's command.

**Comment by crazy-max** [comment]
You can use the OCI or Docker exporter, see https://docs.docker.com/build/exporters/oci-docker/

Also keep in mind that Docker store does not support multi-platform images. You can either enable containerd snapshotter as shown in https://docs.docker.com/storage/containerd/?highlight=containerd or export your image matching the platform of the targeted host.
