### ISSUE TITLE
action suddenly failing with no change in workflows

### ISSUE THREAD

**Issue by igor47** [docker/setup-buildx-action#358]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/setup-buildx-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

the action repeatedly fails. here's the error:
![image](https://github.com/user-attachments/assets/7095da1d-576c-4a17-8fa1-485dfa790202)

or as text:
```
Booting builder
  /usr/bin/docker buildx inspect --bootstrap --builder builder-85d1d6d9-4699-4473-8322-ba8e5611d0ea
  #1 [internal] booting buildkit
  #1 pulling image moby/buildkit:buildx-stable-1
  #1 pulling image moby/buildkit:buildx-stable-1 0.2s done
  #1 ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password
  ------
   > [internal] booting buildkit:
  ------
  ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password
Error: The process '/usr/bin/docker' failed with exit code 1
```

### Expected behaviour

it should set up buildx

### Actual behaviour

the action fails

### YAML workflow

```yaml
- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
```
```


### Workflow logs

```
Run docker/setup-buildx-action@v2
  with:
    driver: docker-container
    buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    install: false
    use: true
    cleanup: true
Docker info
  /usr/bin/docker version
  Client: Docker Engine - Community
   Version:           26.1.3
   API version:       1.45
   Go version:        go1.21.10
   Git commit:        b72abbb
   Built:             Thu May 16 08:33:29 2024
   OS/Arch:           linux/amd64
   Context:           default
  
  Server: Docker Engine - Community
   Engine:
    Version:          26.1.3
    API version:      1.45 (minimum version 1.24)
    Go version:       go1.21.10
    Git commit:       8e96db1
    Built:            Thu May 16 08:33:29 2024
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.7.22
    GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
   runc:
    Version:          1.1.14
    GitCommit:        v1.1.14-0-g2c9f560
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /usr/bin/docker info
  Client: Docker Engine - Community
   Version:    26.1.3
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.17.1
      Path:     /usr/libexec/docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.27.1
      Path:     /usr/libexec/docker/cli-plugins/docker-compose
  
  Server:
   Containers: 0
    Running: 0
    Paused: 0
    Stopped: 0
   Images: 15
   Server Version: 26.1.3
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: false
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
   runc version: v1.1.14-0-g2c9f560
   init version: de40ad0
   Security Options:
    apparmor
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 6.8.0-1014-azure
   Operating System: Ubuntu 22.04.5 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 2
   Total Memory: 7.753GiB
   Name: fv-az1715-685
   ID: 50f520d9-697c-4217-af0f-2af166f71cd2
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: githubactions
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
  
Buildx version
  /usr/bin/docker buildx version
  github.com/docker/buildx v0.17.1 257815a6fbaee88976808020bf04274388275ae8
Creating a new builder instance
  /usr/bin/docker buildx create --name builder-85d1d6d9-4699-4473-8322-ba8e5611d0ea --driver docker-container --buildkitd-flags --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host --use
  builder-85d1d6d9-4699-4473-8322-ba8e5611d0ea
Booting builder
  /usr/bin/docker buildx inspect --bootstrap --builder builder-85d1d6d9-4699-4473-8322-ba8e5611d0ea
  #1 [internal] booting buildkit
  #1 pulling image moby/buildkit:buildx-stable-1
  #1 pulling image moby/buildkit:buildx-stable-1 0.2s done
  #1 ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password
  ------
   > [internal] booting buildkit:
  ------
  ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1": unauthorized: incorrect username or password
Error: The process '/usr/bin/docker' failed with exit code 1
```

### BuildKit logs

_No response_

### Additional info

_No response_

**Comment by azlyth** [comment]
Yeah I'm seeing this too. I'm thinking some kind of Docker Hub issue.

**Comment by NERLOE** [comment]
I'm having the same problem too.

**Comment by ArneClaerebout** [comment]
Same issue here

**Comment by oldmanz** [comment]
Same error here!

Holding up our deployment.  I wonder if Docker Hub just added the need for credentials when getting buildkit?

**Comment by michaelfarrell76** [comment]
same here!

**Comment by shantamg** [comment]
same here!

**Comment by kevin-presalytics** [comment]
I am also receiving this error.  Seems like Docker Hub just changed the auth policy for moby/buildkit.

**Comment by tpyle** [comment]
It does seem to be an issue in docker hub, doing a HEAD request to `https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1` returns a 401, although pulling the image (`docker pull moby/buildkit:buildx-stable-1`) works

**Comment by eslamelhadedy** [comment]
i have the same issue

**Comment by AndroAmater** [comment]
Same here

**Comment by omar-729** [comment]
Same here

**Comment by yavilavi** [comment]
Same here

**Comment by oldmanz** [comment]
I can't find anything concrete, but I think that docker hub may have updated to require logins when accessing the manifest api?

I'm gonna try to login with a throw away account to try getting around this.

**Comment by aud** [comment]
There's an active incident: https://www.dockerstatus.com/

**Comment by film42** [comment]
From : https://www.dockerstatus.com/
> Anonymous pulls and password auth continue to work.

![image](https://github.com/user-attachments/assets/3f090e91-aac1-4b4e-a3ec-31af5e794a4b)

**Comment by VictorGaiva** [comment]
Using Google's artifact registry but still having the same issue.

**Comment by yavilavi** [comment]
https://www.dockerstatus.com/

![image](https://github.com/user-attachments/assets/4c4e1bda-ba14-4999-9242-6c802fae4f76)

**Comment by lingxi-at-contextual** [comment]
We are on a forest fire 🔥

**Comment by devdammit** [comment]
Our CI/CD pipelines
![You Have Failed](https://github.com/user-attachments/assets/d7b0b9d2-df3f-4abf-8cd6-88a430218406)

**Comment by alexandrospanayi** [comment]
Everyone having a nice Friday? :)

**Comment by eslamelhadedy** [comment]
a7a by egypt

**Comment by jwtly10** [comment]
thought i was going crazy :(

**Comment by aldompe95** [comment]
Friday vibes

![image](https://github.com/user-attachments/assets/81ea1b80-3d8c-4a10-8199-4c4d1bf09f0c)

**Comment by focux** [comment]
And that folks, it's the reason why you never deploy on friday

**Comment by yavilavi** [comment]
![image](https://github.com/user-attachments/assets/be61ebcb-ce13-4c38-8f94-0057f3152bd2)

**Comment by DemonICOLI** [comment]
![mpbx41dkttm81](https://github.com/user-attachments/assets/10b9f766-2970-44ed-a28d-88f57e160288)

**Comment by DemonICOLI** [comment]
A workaround is to manually run `doker logout` before the action itself

**Comment by CumpsD** [comment]
This works as a workaround, doing `docker logout` first:

```yaml
      - name: Fix Docker Hub Issue
        run: docker logout
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by burakcansoy** [comment]
I have become incident, the destroyer of deploys

**Comment by herberthobregon** [comment]
Here are all the people who deploy on a Friday? Do it on Monday 😂

**Comment by eslamelhadedy** [comment]
also this work for me 
`    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin`

**Comment by minusworld** [comment]
We set up a mirror for the time being while the upstream incident is resolved: https://docs.docker.com/build/ci/github-actions/configure-builder/#registry-mirror

```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"] 
```

**Comment by data-if** [comment]
> This works as a workaround, doing `docker logout` first:
> 
> ```yaml
>       - name: Fix Docker Hub Issue
>         run: docker logout
>         
>       - name: Set up Docker Buildx
>         id: buildx
>         uses: docker/setup-buildx-action@v3.6.1
> 
>       - name: Login to GitHub Container Registry
>         uses: docker/login-action@v3.3.0
>         with:
>           registry: ${{ env.DOCKER_REGISTRY }}
>           username: ${{ github.repository_owner }}
>           password: ${{ secrets.GITHUB_TOKEN }}
> ```

nice, work for my case

**Comment by tonistiigi** [comment]
This was hub-side issue with personal access tokens. Should be resolved now.

https://www.dockerstatus.com/

> September 27, 2024 14:20 PDT
September 27, 2024 21:20 UTC[Monitoring] Access Tokens are working again, and error rates have returned to normal. Will continue to monitor.

**Comment by igor47** [comment]
> Here are all the people who deploy on a Friday? Do it on Monday 😂

we build docker images as part of our CI flow. just because we build an image doesn't mean we intend to deploy it, but we require the build to succeed to merge to `main`.

**Comment by hablutzel1** [comment]
Happening again and https://www.dockerstatus.com reporting:

> September 24, 2025 16:19 PDT
> September 24, 2025 23:19 UTC [Identified] We have identified the cause and are working on implementing a fix. 
> 
> September 24, 2025 16:09 PDT
> September 24, 2025 23:09 UTC [Investigating] We are investigating elevated error rates for authentication requests on [hub.docker.com](http://hub.docker.com/) and the Docker Hub Registry APIs.
