### ISSUE TITLE
DNS Resolution stopped working

### ISSUE THREAD

**Issue by what5150** [docker/setup-buildx-action#378]
Starting 2024-11-08, my build-push-action@v6 steps started failing with exit status 128 and a fatal error "Could not resolve host: yyy.xxxx.com". The only way I could get DNS working again in the build and push step was to add "driver-opts: network=host" to the setup-buildx-action@v3 steps. There haven't been any infrastructure changes, no changes to the runner or its host, the workflow hasn't been edited in months. The runner is on docker, so I spun up another runner on bare metal just to test and had the same issue. Not sure what would cause this.

**Comment by ndguarino** [comment]
Just verifying this is also happening on Github-hosted runners, not just self-hosted. Able to reproduce with standard runner size, ubuntu-latest image. Workaround above works.

This is likely an upstream issue in actions/runner.

**Comment by crazy-max** [comment]
@what5150 @ndguarino Can you create a [bug report](https://github.com/docker/setup-buildx-action/issues/new?template=bug.yml) please to help us figure out what's going on?

**Comment by what5150** [comment]
@crazy-max  Will do.

**Comment by crazy-max** [comment]
@what5150 Thanks! If you can just post a link of your repo where this issue occurs that would be great as well!

**Comment by what5150** [comment]
@crazy-max I can't link the repo; org policy, but I did add workflow and build log.

**Comment by crazy-max** [comment]
Let's tracked this in #379
