### ISSUE TITLE
Package selection during buildx build

### ISSUE THREAD

**Issue by ska-ibees** [docker/setup-buildx-action#41]
Hello,

In the scenerio where platform specific dependency is required. What would the best approach to build multiplatform images?

For example:

There are two variants of wkhtmltopdf:
1. wkhtmltopdf_0.12.5-1_**arm64**.deb
2. wkhtmltopdf_0.12.5-1_**amd64**.deb

So, is it possible to use a single Dockerfile with some condition that buildx can interpret? Or any other better way to achieve it? 

Thanks

**Comment by tonistiigi** [comment]
See https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
