### ISSUE TITLE
v1.0.4 seems to mess up the order of multi-stage/multi-arch build (failed to compute cache key: failed to copy)

### ISSUE THREAD

**Issue by jesec** [docker/setup-buildx-action#44]
v1.0.4 breaks things hard. It should NOT be a patch release.

If there is breaking change, the release needs to be a MAJOR release. Otherwise, people who rely on current behavior are going to notice that their CI starts to fail for mysterious reasons. 

If there is a behavior change, the changes should be documented. It is definitely inappropriate to release such change as a patch release.

#### Steps to reproduce this issue

1. Use v1.0.4 and CI fails.
2. Use v1.0.3 and CI succeeds. 

#### Actual behaviour

CI fails with v1.0.4. It works fine with v1.0.3.

### Configuration

* Repository URL (if public): [https://github.com/jesec/flood](https://github.com/jesec/flood)
* Build URL (if public): 
  * Fails with v1.0.4: https://github.com/jesec/flood/runs/1545071699
  * Succeeds after https://github.com/jesec/flood/commit/0d785f92be307a9c2b97885c60660c6c31f0c6ba: [https://github.com/jesec/flood/runs/1550522236](https://github.com/jesec/flood/runs/1550522236)

`setup-buildx-action` is the only action that was updated recently. 

### Logs

<details>

<summary>failed to solve: rpc error: code = Canceled desc = failed to compute cache key: failed to copy: httpReadSeeker: failed open: failed to do request: context canceled</summary>

```
/usr/bin/docker buildx build --tag ***/flood:master --platform linux/amd64,linux/arm64,linux/arm/v7 --iidfile /tmp/docker-build-push-sjnerH/iidfile --file ./Dockerfile --push .
time="2020-12-13T08:36:12Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 30B 0.0s
#1 transferring dockerfile: 1.16kB 0.0s done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 690B done
#2 DONE 0.0s

#3 [linux/amd64 internal] load metadata for docker.io/library/node:alpine
#3 DONE 0.3s

#5 [linux/arm64 internal] load metadata for docker.io/library/node:alpine
#5 DONE 0.3s

#4 [linux/arm/v7 internal] load metadata for docker.io/library/node:alpine
#4 DONE 0.5s

#31 [linux/arm64 flood 1/6] FROM docker.io/library/node:alpine@sha256:4f06b5...
#31 resolve docker.io/library/node:alpine@sha256:4f06b5623fde05abe6df71c1f18beb079e455c8edf89a233a56d225af1e46ca5 0.0s done
#31 ...

#6 [linux/arm/v7 flood 1/6] FROM docker.io/library/node:alpine@sha256:4f06b...
#6 DONE 0.2s

#31 [linux/arm64 flood 1/6] FROM docker.io/library/node:alpine@sha256:4f06b5...
#31 sha256:75f4eb1f919fd7ee50816fdf758a5be77932b0c954e0b073fce9efbce8d2ef3b 279B / 279B 0.1s
#31 sha256:b85f0771c80dd8734b81bf419ea12a13f40c84b6a8e7995af03c75223f8e5748 0B / 2.30MB 0.0s
#31 sha256:d991611c9711db9b8355e5e411c35afcb3599d70d3a7fbffb81c20efd94a7859 0B / 35.45MB 0.0s
#31 sha256:29e5d40040c18c692ed73df24511071725b74956ca1a61fe6056a651d86a13bd 0B / 2.72MB
#31 DONE 0.1s

#8 [linux/amd64 nodebuild 1/7] FROM docker.io/library/node:alpine@sha256:4f...
#8 resolve docker.io/library/node:alpine@sha256:4f06b5623fde05abe6df71c1f18beb079e455c8edf89a233a56d225af1e46ca5 0.0s done
#8 sha256:263ad63ca75dfd6f1fd4f9815a04d4f627d4eb57eaa466ba848eeae2ca8b444e 0B / 2.24MB
#8 sha256:983b645ea0db7972d47d5609833b678886f7c14b389b59b08c9a6df417b4dc27 0B / 34.82MB
#8 sha256:5fbdd057992a6a6f2a9ae21d8eb594a31a0b53a60b4ad5b542e138231ef1c10a 0B / 280B
#8 sha256:cbdbe7a5bc2a134ca8ec91be58565ec07d037386d1f1d8385412d224deafca08 0B / 2.81MB
#8 DONE 0.0s

#9 [linux/amd64 nodebuild 2/7] WORKDIR /usr/src/app/
#9 CANCELED

#20 [linux/amd64 flood 2/6] RUN rm -rf /tmp/*
#20 CANCELED

#33 [linux/amd64 nodebuild 2/7] WORKDIR /usr/src/app/
#33 CANCELED

#10 [internal] load build context
#10 transferring context: 4.62MB 0.4s done
#10 CANCELED

#21 [linux/amd64 nodebuild 2/7] WORKDIR /usr/src/app/
#21 CANCELED

#6 [linux/arm/v7 flood 1/6] FROM docker.io/library/node:alpine@sha256:4f06b...
#6 sha256:a0387227646468c45d235a8bc6000de858bcd75d1e85c33f12ec81573a5ad31f 279B / 279B 0.0s done
#6 sha256:96bad5ae163c75ab0d5b1d2cf9d266b4e4b02f91da694b4da9250b78a1a7c923 2.29MB / 2.29MB 0.1s
#6 sha256:1ec83a9cffbb8d2f3e7a3f32c1aee90be250f7768f491686333084dd843cbbd1 4.19MB / 34.06MB 0.1s
#6 sha256:3cfb62949d9d8613854db4d5fe502a9219c2b55a153043500078a64e880ae234 2.42MB / 2.42MB 0.1s
#6 extracting sha256:3cfb62949d9d8613854db4d5fe502a9219c2b55a153043500078a64e880ae234
#6 extracting sha256:3cfb62949d9d8613854db4d5fe502a9219c2b55a153043500078a64e880ae234 done
#6 DONE 0.2s

#32 [linux/arm64 flood 2/6] RUN rm -rf /tmp/*
#32 CANCELED

#7 [linux/arm/v7 flood 2/6] RUN rm -rf /tmp/*
#7 CANCELED
failed to solve: rpc error: code = Canceled desc = failed to compute cache key: failed to copy: httpReadSeeker: failed open: failed to do request: context canceled
```

</details>

**Comment by crazy-max** [comment]
@jesec 

* `v1.0.3` was using the `moby/buildkit:v0.8-beta` buildkit image which was a [temporary fix for blocking issues on build-push-action](https://github.com/docker/setup-buildx-action/pull/27)
* `v1.0.4` removes this temporary fix and now uses the legit stable release of buildkit image `moby/buildkit:buildx-stable-1` (buildkit v0.8.0 atm).

> `failed to solve: rpc error: code = Canceled desc = failed to compute cache key: failed to copy: httpReadSeeker: failed open: failed to do request: context canceled`

About this error, I think @tonistiigi managed to repro. If you want to rely on the beta in your workflow you can stick to it with:

```yaml
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
       with:
         driver-opts: image=moby/buildkit:v0.8-beta
```

Sorry for the inconvenience

**Comment by crazy-max** [comment]
@jesec PRs that could fix your issue (moby/buildkit#1871 and moby/buildkit#1891) have been merged. Can you try with the following step please?:

```yaml
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
       with:
         buildkitd-flags: --debug
```

Thanks

**Comment by jesec** [comment]
https://github.com/jesec/flood/runs/1555229248

**Comment by crazy-max** [comment]
@jesec Ok looks like it's fixed. Feel free to close this issue thanks!

**Comment by jesec** [comment]
> @jesec Ok looks like it's fixed. Feel free to close this issue thanks!

Thanks. Good job.
