### ISSUE TITLE
Passing secret as ARGs

### ISSUE THREAD

**Issue by mbajur** [docker/setup-buildx-action#52]
Technically it's not a bug but a question so please pardon my ignorance if you're not providing this kind of support in here. 

The thing is - my Dockerfile depends on a ARG containing private ruby gem package registry credentials. Does this action provide a support for passing action secrets as build args?

Thanks in advance for help.

**Comment by crazy-max** [comment]
@mbajur This action only takes care of setting up buildx. To build your image you must refer to our [build-push-action](https://github.com/docker/build-push-action/) which allows to pass [secrets and args](https://github.com/docker/build-push-action/#inputs).

**Comment by mbajur** [comment]
To be honest...i have no idea what i was thinking yesterday while asking that question. It's pretty obvious this action is not responsible for building the image. I already solved my issue using build-push-action. Thank you for your assistance!
