### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by crazy-max** [docker/setup-buildx-action#64]
While boostraping a builder, I encountered the [following exception](https://github.com/crazy-max/artifactory-cleanup/runs/2261223392?check_suite_focus=true#step:3:17):

```
  /usr/bin/docker buildx inspect --bootstrap --builder builder-8911b936-26d9-48a2-8170-162f38eb730e
  #1 [internal] booting buildkit
  #1 sha256:3caa0fb6ce20487f1e7f91f51b4919a58916b18bd26a2a507e41f4b5250c9946
  #1 pulling image moby/buildkit:buildx-stable-1
  #1 pulling image moby/buildkit:buildx-stable-1 15.0s done
  #1 ERROR: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  ------
   > [internal] booting buildkit:
  ------
  Name:   builder-8911b936-26d9-48a2-8170-162f38eb730e
  Driver: docker-container
  
  Nodes:
  Name:     builder-8911b936-26d9-48a2-8170-162f38eb730e0
  Endpoint: unix:///var/run/docker.sock
  Error:    Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

The action step should fail on [`docker buildx inspect --bootstrap ...`](https://github.com/docker/setup-buildx-action/blob/03951fea2c6e767acb1d25d82de2d73c711366c1/src/main.ts#L59) because that's the default behavior in the [toolkit interface](https://github.com/actions/toolkit/blob/af821474235d3c5e1f49cee7c6cf636abb0874c4/packages/exec/src/interfaces.ts#L27-L28). So I think that's an issue with buildx. WDYT @tonistiigi?

**Comment by tonistiigi** [comment]
Looks like a network timeout when connecting to hub to pull buildkit image. The error doesn't come from buildx but from docker directly.

**Comment by crazy-max** [comment]
@tonistiigi 

> The error doesn't come from buildx but from docker directly.

Yes that's it so should be handled [here in buildx](https://github.com/docker/buildx/blob/adc5f35237001636752235b74bb0110a3af69c42/driver/docker-container/driver.go#L70). Error doesn't seem processed.
