### ISSUE TITLE
Question: Where can I find all available platforms?

### ISSUE THREAD

**Issue by pascalandy** [docker/setup-buildx-action#88]
[Here we see](https://github.com/marketplace/actions/docker-setup-buildx#outputs): 

![Screen Shot 2021-06-22 at 9 40 02 AM](https://user-images.githubusercontent.com/6694151/122934800-d8481300-d33d-11eb-8100-4d50dbb7d725.jpg)

Cool, but where can I find all available platforms for buildx?

This is what I have so far.

```
      -
        name: MASTER | buildx and push all tags | multi-platforms
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ env.DOCKERFILE }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/i386
            linux/mips64le
            linux/ppc64le
            linux/s390x
            windows/amd64
```

Are they correct? Is there more to this list?

**Comment by crazy-max** [comment]
@pascalandy Platforms available are dependent of the host. In the case of GitHub Runners (`ubuntu-latest`), default platforms available are `linux/amd64,linux/386`. If you want to add support for more platforms you can use our [setup-qemu-action](https://github.com/docker/setup-qemu-action) as shown in the [README](https://github.com/docker/setup-buildx-action#with-qemu). Under the hood it uses the [binfmt](https://github.com/tonistiigi/binfmt#binfmt) image to install qemu-user emulator binaries.

**Comment by pascalandy** [comment]
Thanks for replying!

Yes I use qemu as well. 

This answers my question :)
https://github.com/tonistiigi/binfmt#build-test-image

**Comment by crazy-max** [comment]
You can also find this info in the logs of the qemu action as shown in [this screenshot](https://github.com/docker/setup-qemu-action#about).

**Comment by pascalandy** [comment]
Cool, I can see this as well in my builds :)
